[package]
name = "example_rgb_camera_visualization"
edition = "2021"
publish = false

[dependencies]
foxglove = { path = "../../foxglove" }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
anyhow = "1.0"
opencv = { version = "0.95", default-features = false, features = ["videoio"] }
