#include <string>

#include <gtest/gtest.h>

#include <foxglove_bridge/message_definition_cache.hpp>

using foxglove_bridge::MessageDefinitionCache;
using foxglove_bridge::MessageDefinitionFormat;

TEST(MessageDefinitionCacheTest, ServiceRequest) {
  MessageDefinitionCache cache;
  const auto [format, text] = cache.get_full_text("std_srvs/srv/SetBool_Request");
  EXPECT_EQ(format, MessageDefinitionFormat::MSG);
  EXPECT_NE(std::string::npos, text.find("bool data"));
}

#if __has_include(<service_msgs/msg/service_event_info.hpp>)
TEST(MessageDefinitionCacheTest, ServiceEvent) {
  // <Srv>_Event messages are generated by rosidl for service introspection and have no
  // definition file of their own; the cache synthesizes them.
  MessageDefinitionCache cache;
  const auto [format, text] = cache.get_full_text("std_srvs/srv/SetBool_Event");
  EXPECT_EQ(format, MessageDefinitionFormat::MSG);
  EXPECT_NE(std::string::npos, text.find("service_msgs/msg/ServiceEventInfo info"));
  EXPECT_NE(std::string::npos, text.find("std_srvs/srv/SetBool_Request[<=1] request"));
  EXPECT_NE(std::string::npos, text.find("std_srvs/srv/SetBool_Response[<=1] response"));
  // Dependency definitions are embedded in the full text.
  EXPECT_NE(std::string::npos, text.find("MSG: std_srvs/srv/SetBool_Request"));
  EXPECT_NE(std::string::npos, text.find("MSG: std_srvs/srv/SetBool_Response"));
  EXPECT_NE(std::string::npos, text.find("MSG: service_msgs/msg/ServiceEventInfo"));
  // ServiceEventInfo's own dependencies are resolved transitively. (ServiceEventInfo.msg
  // references the type as "builtin_interfaces/Time", without the "msg/" segment.)
  EXPECT_NE(std::string::npos, text.find("MSG: builtin_interfaces/Time"));
}

TEST(MessageDefinitionCacheTest, ActionSendGoalEvent) {
  // Actions get service events for their implicit _SendGoal and _GetResult services.
  MessageDefinitionCache cache;
  const auto [format, text] = cache.get_full_text("test_msgs/action/Fibonacci_SendGoal_Event");
  EXPECT_EQ(format, MessageDefinitionFormat::MSG);
  EXPECT_NE(std::string::npos, text.find("service_msgs/msg/ServiceEventInfo info"));
  EXPECT_NE(std::string::npos,
            text.find("test_msgs/action/Fibonacci_SendGoal_Request[<=1] request"));
  EXPECT_NE(std::string::npos,
            text.find("test_msgs/action/Fibonacci_SendGoal_Response[<=1] response"));
  EXPECT_NE(std::string::npos, text.find("MSG: test_msgs/action/Fibonacci_SendGoal_Request"));
  EXPECT_NE(std::string::npos, text.find("MSG: test_msgs/action/Fibonacci_SendGoal_Response"));
}

TEST(MessageDefinitionCacheTest, ActionGetResultEvent) {
  MessageDefinitionCache cache;
  const auto [format, text] = cache.get_full_text("test_msgs/action/Fibonacci_GetResult_Event");
  EXPECT_EQ(format, MessageDefinitionFormat::MSG);
  EXPECT_NE(std::string::npos, text.find("service_msgs/msg/ServiceEventInfo info"));
  EXPECT_NE(std::string::npos,
            text.find("test_msgs/action/Fibonacci_GetResult_Request[<=1] request"));
  EXPECT_NE(std::string::npos,
            text.find("test_msgs/action/Fibonacci_GetResult_Response[<=1] response"));
}
#endif

TEST(MessageDefinitionCacheTest, UnknownTypeThrows) {
  MessageDefinitionCache cache;
  EXPECT_THROW(cache.get_full_text("std_msgs/msg/DoesNotExist"),
               foxglove_bridge::DefinitionNotFoundError);
}
