services:
  livekit:
    # Using latest so that if livekit breaks something we find out in CI rather than production (better ideas welcome)
    image: livekit/livekit-server:latest
    # Firefox won't connect to 127.0.0.1 for WebRTC, so set another IP here for Firefox
    command:
      [
        "--dev",
        "--bind",
        "0.0.0.0",
        "--node-ip",
        "${LIVEKIT_NODE_IP:-127.0.0.1}",
        "--config-body",
        "enable_data_tracks: true",
      ]
    ports:
      - "7880:7880" # HTTP / WebSocket
      - "7881:7881" # RTC over TCP
      - "7882:7882/udp" # RTC over UDP
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7880"]
      interval: 2s
      timeout: 5s
      retries: 15
