// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Pose } from "./Pose";
import { Time } from "./Time";

/** A compressed point cloud. A decoder for `format` must decompress `data`, using metadata stored in the compressed payload to recover point positions and any additional per-point attributes. The decoded point cloud must include at least 2 coordinate fields from `x`, `y`, and `z`; `red`, `green`, `blue`, and `alpha` are optional for customizing each point's color. */
export type CompressedPointCloud = {
  /** Timestamp of point cloud */
  timestamp: Time;

  /** Frame of reference */
  frame_id: string;

  /** The origin of the point cloud relative to the frame of reference */
  pose: Pose;

  /** Compressed point cloud data for exactly one point cloud, including any format-specific metadata needed to describe the decoded point attributes. */
  data: Uint8Array;

  /**
   * Point cloud compression format.
   * 
   * Supported values: `draco` ([Google Draco](https://google.github.io/draco/)).
   */
  format: string;
};
