// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A duration of time, composed of seconds and nanoseconds */
export type Duration = {
  /** The number of seconds in the duration */
  sec: number;

  /** The number of nanoseconds in the positive direction */
  nsec: number;
};
