// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { KeyValuePair } from "./KeyValuePair";
import { Time } from "./Time";

/** A discrete event that occurred over a time range */
export type Event = {
  /** Event start time (inclusive) */
  start_time: Time;

  /** Event end time (inclusive) */
  end_time: Time;

  /** Additional key-value metadata. Keys must be unique. */
  metadata?: KeyValuePair[];
};
