// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { CircleAnnotation } from "./CircleAnnotation";
import { KeyValuePair } from "./KeyValuePair";
import { PointsAnnotation } from "./PointsAnnotation";
import { TextAnnotation } from "./TextAnnotation";
import { Time } from "./Time";

/** Array of annotations for a 2D image */
export type ImageAnnotations = {
  /** Timestamp of the image annotations. When set, individual annotation timestamps will be ignored. */
  timestamp?: Time;

  /** Circle annotations */
  circles: CircleAnnotation[];

  /** Points annotations */
  points: PointsAnnotation[];

  /** Text annotations */
  texts: TextAnnotation[];

  /** Additional user-provided metadata associated with the image annotations. Keys must be unique within this object. Per-annotation metadata takes precedence over these values. */
  metadata?: KeyValuePair[];
};
