// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { KeyValuePair } from "./KeyValuePair";
import { Pose } from "./Pose";
import { Time } from "./Time";
import { Vector3 } from "./Vector3";

/** An estimate of position, orientation, and velocity for an object or reference frame in 3D space */
export type Odometry = {
  /** Timestamp of the message */
  timestamp: Time;

  /** Reference coordinate frame (e.g. `map` or `odom`) */
  frame_id: string;

  /** Coordinate frame of the body whose motion is being estimated (e.g. `base_link`) */
  body_frame_id: string;

  /** Position and orientation of body_frame_id in frame_id */
  pose: Pose;

  /** Linear velocity in m/s in body_frame_id */
  linear_velocity?: Vector3;

  /** Angular velocity in rad/s in body_frame_id */
  angular_velocity?: Vector3;

  /** Row-major 6x6 covariance matrix (x, y, z, rotation about x, rotation about y, rotation about z). Set to zero if unknown. */
  pose_covariance?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

  /** Row-major 6x6 covariance matrix (vx, vy, vz, angular rate about x, angular rate about y, angular rate about z). Set to zero if unknown. */
  velocity_covariance?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

  /** Additional user-provided metadata associated with the odometry message. Keys must be unique. */
  metadata?: KeyValuePair[];
};
