// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single block of an audio bitstream */
export type RawAudio = {
  /** Timestamp of the start of the audio block */
  timestamp: Time;

  /** Audio data. The samples in the data must be interleaved and little-endian */
  data: Uint8Array;

  /** Audio format. Only 'pcm-s16' is currently supported */
  format: string;

  /** Sample rate in Hz */
  sample_rate: number;

  /** Number of channels in the audio block */
  number_of_channels: number;
};
