// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single block of an audio bitstream */
export type RawAudio = {
  /** Timestamp of the start of the audio block */
  timestamp: Time;

  /**
   * Raw audio data without WAV, container, or RTP headers. Samples must be interleaved. Multibyte samples must be little-endian.
   * 
   * For each `format` value, the `data` field contains audio sample data serialized as follows:
   * 
   * - `pcm-s16`:
   *   - Each sample is a signed 16-bit PCM value.
   *   - The byte length must be divisible by `2 * number_of_channels` so the block contains complete sample frames.
   * - `g711-alaw`:
   *   - Each byte is one G.711 A-law encoded sample.
   *   - The byte length must be divisible by `number_of_channels` so the block contains complete sample frames.
   * - `g711-ulaw`:
   *   - Each byte is one G.711 mu-law encoded sample.
   *   - The byte length must be divisible by `number_of_channels` so the block contains complete sample frames.
   */
  data: Uint8Array;

  /** Format of the audio data. See the `data` field description for supported values. Consumers may support a subset of these formats. */
  format: string;

  /** Sample rate in Hz. This must be greater than zero. */
  sample_rate: number;

  /** Number of channels in the audio block. This must be greater than zero. */
  number_of_channels: number;
};
