// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A vector in 3D space that represents a direction only */
export type Vector3 = {
  /** x component */
  x: number;

  /** y component */
  y: number;

  /** z component */
  z: number;
};
