// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A vector in 2D space that represents a direction only */
export type Vector2 = {
  /** x component */
  x: number;

  /** y component */
  y: number;
};
