// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { PackedElementField } from "./PackedElementField";
import { Pose } from "./Pose";
import { Time } from "./Time";
import { Vector3 } from "./Vector3";

/** A 3D grid of data */
export type VoxelGrid = {
  /** Timestamp of grid */
  timestamp: Time;

  /** Frame of reference */
  frame_id: string;

  /** Origin of grid's corner relative to frame of reference */
  pose: Pose;

  /** Number of grid rows */
  row_count: number;

  /** Number of grid columns */
  column_count: number;

  /** Size of single grid cell along x, y, and z axes, relative to `pose` */
  cell_size: Vector3;

  /** Number of bytes between depth slices in `data` */
  slice_stride: number;

  /** Number of bytes between rows in `data` */
  row_stride: number;

  /** Number of bytes between cells within a row in `data` */
  cell_stride: number;

  /** Fields in `data`. `red`, `green`, `blue`, and `alpha` are optional for customizing the grid's color. */
  fields: PackedElementField[];

  /**
   * Grid cell data, interpreted using `fields`, in depth-major, row-major (Z-Y-X) order.
   * For the data element starting at byte offset i, the coordinates of its corner closest to the origin will be:
   * 
   * - z = i / slice_stride * cell_size.z
   * - y = (i % slice_stride) / row_stride * cell_size.y
   * - x = (i % row_stride) / cell_stride * cell_size.x
   */
  data: Uint8Array;
};
