[package]
name = "example_channelless"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", features = ["schemars"] }
env_logger = "0.11.5"
mcap.workspace = true
schemars = "1.0.4"
serde = { version = "1.0", features = ["derive"] }
