[package]
name = "example_mcap"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", default-features = false, features = ["derive", "lz4", "schemars", "zstd"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
schemars = "1.0.4"
serde = { version = "1.0", features = ["derive"] }
