[package]
name = "example_structured_logging"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bytes = "1.10"
env_logger = "0.11"
foxglove = { path = "../../foxglove", default-features = false, features = ["derive", "schemars"] }
schemars = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.142"

[lints]
workspace = true
