[package]
name = "example_param_server"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", features = ["unstable"] }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
