# CMake package config for the foxglove SDK redistributable dist. Hand-written (not
# generated by configure_package_config_file) and shipped verbatim by Container.mk's
# build-cpp-dist recipe; the dist places it at lib/cmake/foxglove-sdk/foxglove-sdkConfig.cmake.
#
# This is distinct from the local-install package config (cpp/cmake/foxglove-sdkConfig.cmake.in)
# because the dist and the local install ship different things: the local install ships a
# prebuilt foxglove_cpp_shared/_static; the dist ships C++ wrapper sources and asks consumers
# to compile them against their own toolchain. The two configs describe different surfaces.
#
# Consumer usage:
#   find_package(foxglove-sdk CONFIG REQUIRED HINTS /path/to/dist)
#   foxglove_sdk_add_cpp_library(my_foxglove_cpp
#       TYPE SHARED                       # or STATIC
#       REMOTE_ACCESS ON                  # or OFF
#   )
#   target_link_libraries(my_app PRIVATE my_foxglove_cpp)
#
# The dist always ships libfoxglove.a (non-RA static C lib) and libfoxglove.so (RA cdylib).
# A non-RA shared C lib and an RA static C lib are not shipped — see the helper for the
# supported (TYPE, REMOTE_ACCESS) combinations.

# Compute the dist root from this file's location:
#   <prefix>/lib/cmake/foxglove-sdk/foxglove-sdkConfig.cmake  → up 3 → <prefix>
get_filename_component(_foxglove_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Records the actual remote-access flavor of the shipped cdylib. Container.mk's
# build-cpp-dist writes this file alongside this config; it sets
# FOXGLOVE_SDK_CDYLIB_REMOTE_ACCESS to ON or OFF to reflect whether libfoxglove.so
# was built with --features remote-access. The helper below uses it to reject
# REMOTE_ACCESS=ON requests against a non-RA dist instead of silently producing
# a wrapper that links the wrong cdylib.
include("${CMAKE_CURRENT_LIST_DIR}/dist-flavor.cmake")

# Standard check_required_components macro for find_package(... COMPONENTS ...).
macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

set(_foxglove_lib_dir "${_foxglove_prefix}/lib")
set(_foxglove_include_dir "${_foxglove_prefix}/include")
set(_foxglove_src_dir "${_foxglove_prefix}/src")

# Import the prebuilt Rust/C library targets. The dist puts all libs (including
# the .dll on Windows) under lib/ rather than splitting per GNUInstallDirs, so a
# single dir works for both STATIC_LIB and SHARED_LIB. The helper applies the
# platform link libs to foxglove-static and handles the Windows import library.
include("${CMAKE_CURRENT_LIST_DIR}/foxglove-c-imports.cmake")
foxglove_sdk_import_c_libs(
  STATIC_LIB "${_foxglove_lib_dir}/${CMAKE_STATIC_LIBRARY_PREFIX}foxglove${CMAKE_STATIC_LIBRARY_SUFFIX}"
  SHARED_LIB "${_foxglove_lib_dir}/${CMAKE_SHARED_LIBRARY_PREFIX}foxglove${CMAKE_SHARED_LIBRARY_SUFFIX}"
  SHARED_IMPLIB "${_foxglove_lib_dir}/foxglove.dll.lib"
)

# C++ wrapper source list, derived from the shared foxglove-sources.cmake file
# (also used by the in-tree build). The dist concatenates handwritten + generated
# because, unlike the in-tree build, consumers compile them all into one wrapper.
include("${CMAKE_CURRENT_LIST_DIR}/foxglove-sources.cmake")
set(FOXGLOVE_SDK_CPP_SOURCES
  ${FOXGLOVE_CPP_HANDWRITTEN_SOURCES}
  ${FOXGLOVE_CPP_GENERATED_SOURCES}
)
list(TRANSFORM FOXGLOVE_SDK_CPP_SOURCES PREPEND "${_foxglove_src_dir}/")
set(FOXGLOVE_SDK_CPP_REMOTE_ACCESS_SOURCES ${FOXGLOVE_CPP_REMOTE_ACCESS_SOURCES})
list(TRANSFORM FOXGLOVE_SDK_CPP_REMOTE_ACCESS_SOURCES PREPEND "${_foxglove_src_dir}/")
set(FOXGLOVE_SDK_INCLUDE_DIRS "${_foxglove_include_dir}")

# foxglove_sdk_add_cpp_library(<name>
#     [TYPE STATIC|SHARED]            # default SHARED
#     [REMOTE_ACCESS ON|OFF]          # default OFF
# )
#
# Compiles the dist's C++ wrapper sources into a library and links the appropriate
# prebuilt C library. Supported (TYPE, REMOTE_ACCESS) combinations:
#   - SHARED + ON  → dynamic-links libfoxglove.so (RA cdylib), adds remote_access.cpp,
#                    defines FOXGLOVE_REMOTE_ACCESS for consumers
#   - SHARED + OFF → statically bundles libfoxglove.a (non-RA) into the SHARED wrapper
#   - STATIC + OFF → static wrapper, propagates libfoxglove.a (non-RA) to consumers
#   - STATIC + ON  → unsupported; the dist does not ship a static RA library because
#                    LiveKit/WebRTC has strict ABI requirements that would leak into
#                    static consumers' binaries.
function(foxglove_sdk_add_cpp_library name)
  cmake_parse_arguments(_arg "" "TYPE;REMOTE_ACCESS" "" ${ARGN})
  if(NOT _arg_TYPE)
    set(_arg_TYPE SHARED)
  elseif(NOT _arg_TYPE STREQUAL "SHARED" AND NOT _arg_TYPE STREQUAL "STATIC")
    message(FATAL_ERROR "foxglove_sdk_add_cpp_library(${name}): TYPE must be SHARED or STATIC (got '${_arg_TYPE}').")
  endif()
  if(NOT _arg_REMOTE_ACCESS)
    set(_arg_REMOTE_ACCESS OFF)
  endif()

  if(_arg_TYPE STREQUAL "STATIC" AND _arg_REMOTE_ACCESS)
    message(FATAL_ERROR "foxglove_sdk_add_cpp_library(${name}): TYPE=STATIC + REMOTE_ACCESS=ON is unsupported; the dist does not ship a static RA library (LiveKit/WebRTC has strict ABI requirements that would leak into static consumers).")
  endif()

  set(_srcs ${FOXGLOVE_SDK_CPP_SOURCES})
  if(_arg_REMOTE_ACCESS)
    list(APPEND _srcs "${FOXGLOVE_SDK_CPP_REMOTE_ACCESS_SOURCES}")
  endif()

  add_library(${name} ${_arg_TYPE} ${_srcs})
  set_target_properties(${name} PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED ON
    POSITION_INDEPENDENT_CODE ON
    WINDOWS_EXPORT_ALL_SYMBOLS ON
  )
  # Headers are shipped by the dist; consumers don't write them, so mark SYSTEM to
  # suppress warnings (consumers' -Wall/-Wextra/-Werror won't flag SDK headers).
  target_include_directories(${name} SYSTEM PUBLIC "${FOXGLOVE_SDK_INCLUDE_DIRS}")

  if(_arg_TYPE STREQUAL "SHARED")
    if(APPLE)
      set_target_properties(${name} PROPERTIES INSTALL_RPATH "@loader_path")
    else()
      set_target_properties(${name} PROPERTIES INSTALL_RPATH "$ORIGIN")
    endif()
  endif()

  # Link visibility differs by wrapper TYPE:
  # - STATIC wrapper: the wrapper.a is just an archive of object files; consumers must
  #   link the underlying C lib themselves at exe link time. PUBLIC propagates it via
  #   the wrapper's INTERFACE_LINK_LIBRARIES.
  # - SHARED wrapper: the wrapper.so encapsulates the C lib (statically bundled for the
  #   non-RA case, dynamically linked via NEEDED for the RA case). Consumers see the
  #   wrapper.so only and shouldn't pick up the underlying C lib on their own link line.
  #   PRIVATE keeps it off INTERFACE_LINK_LIBRARIES.
  if(_arg_TYPE STREQUAL "STATIC")
    set(_link_scope PUBLIC)
  else()
    set(_link_scope PRIVATE)
  endif()

  if(_arg_REMOTE_ACCESS)
    if(NOT TARGET foxglove-shared)
      message(FATAL_ERROR "foxglove_sdk_add_cpp_library(${name}): REMOTE_ACCESS=ON requested but libfoxglove.so was not shipped in this dist.")
    endif()
    if(NOT FOXGLOVE_SDK_CDYLIB_REMOTE_ACCESS)
      message(FATAL_ERROR "foxglove_sdk_add_cpp_library(${name}): REMOTE_ACCESS=ON requested but this dist's libfoxglove.so was built without the remote-access feature. Rebuild the dist with FOXGLOVE_REMOTE_ACCESS=ON (the default).")
    endif()
    target_link_libraries(${name} ${_link_scope} foxglove-shared)
    # The define stays PUBLIC: consumer translation units include foxglove/remote_access.hpp,
    # which depends on foxglove-c/foxglove-c.h's `#if defined(FOXGLOVE_REMOTE_ACCESS)`
    # guards. That's an API-level concern, separate from the link-time encapsulation above.
    target_compile_definitions(${name} PUBLIC FOXGLOVE_REMOTE_ACCESS)
  else()
    if(NOT TARGET foxglove-static)
      message(FATAL_ERROR "foxglove_sdk_add_cpp_library(${name}): no static C library was shipped in this dist.")
    endif()
    target_link_libraries(${name} ${_link_scope} foxglove-static)
  endif()
endfunction()

unset(_foxglove_lib_dir)
unset(_foxglove_include_dir)
unset(_foxglove_src_dir)
unset(_foxglove_prefix)

check_required_components(foxglove-sdk)
