import { generateFlatbuffers } from "./generateFlatbufferSchema";
import { exampleEnum, exampleMessage } from "./testFixtures";
import { FoxgloveMessageSchema, FoxglovePrimitive } from "./types";

describe("generateFlatbuffers", () => {
  it("generates Message .fbs files", () => {
    expect(generateFlatbuffers(exampleMessage, [exampleEnum])).toMatchInlineSnapshot(`
      "// Generated by https://github.com/foxglove/foxglove-sdk

      include "ByteVector.fbs";
      include "Duration.fbs";
      include "NestedMessage.fbs";
      include "Time.fbs";

      namespace foxglove;

      /// An example enum
      enum ExampleEnum : ubyte {
        /// Value A
        A = 0,

        /// Value B
        B = 1,
      }
      /// An example type
      table ExampleMessage {
        /// duration field
        field_duration:Duration (id: 0);

        /// time field
        field_time:Time (id: 1);

        /// boolean field
        field_boolean:bool = true (id: 2);

        /// bytes field
        field_bytes:[uint8] (id: 3);

        /// float64 field
        field_float64:double = 1.0 (id: 4);

        /// uint32 field
        field_uint32:uint32 = 5 (id: 5);

        /// string field
        field_string:string = "string-type" (id: 6);

        /// duration array field
        field_duration_array:[Duration] (id: 7);

        /// time array field
        field_time_array:[Time] (id: 8);

        /// boolean array field
        field_boolean_array:[bool] (id: 9);

        /// bytes array field
        field_bytes_array:[ByteVector] (id: 10);

        /// float64 array field
        field_float64_array:[double] (id: 11);

        /// uint32 array field
        field_uint32_array:[uint32] (id: 12);

        /// string array field
        field_string_array:[string] (id: 13);

        /// duration fixed-length array field
        /// length 3
        field_duration_fixed_array:[Duration] (id: 14);

        /// time fixed-length array field
        /// length 3
        field_time_fixed_array:[Time] (id: 15);

        /// boolean fixed-length array field
        /// length 3
        field_boolean_fixed_array:[bool] (id: 16);

        /// bytes fixed-length array field
        /// length 3
        field_bytes_fixed_array:[ByteVector] (id: 17);

        /// float64 fixed-length array field
        /// length 3
        field_float64_fixed_array:[double] (id: 18);

        /// uint32 fixed-length array field
        /// length 3
        field_uint32_fixed_array:[uint32] (id: 19);

        /// string fixed-length array field
        /// length 3
        field_string_fixed_array:[string] (id: 20);

        /// An enum field
        field_enum:ExampleEnum (id: 21);

        /// An enum array field
        field_enum_array:[ExampleEnum] (id: 22);

        /// A nested field
        field_nested:foxglove.NestedMessage (id: 23);

        /// A nested array field
        /// With
        /// a
        /// very
        /// long
        /// description
        field_nested_array:[foxglove.NestedMessage] (id: 27);

        /// An optional string field
        field_optional_string:string (id: 24);

        /// An optional bool field
        field_optional_bool:bool = null (id: 25);

        /// An optional float64 field
        field_optional_float64:double = null (id: 26);
      }

      root_type ExampleMessage;
      "
    `);
  });

  it("throws on duplicate flatbuffersFieldNumber", () => {
    const schema: FoxgloveMessageSchema = {
      type: "message",
      name: "DuplicateTest",
      description: "test",
      fields: [
        {
          name: "a",
          description: "field a",
          type: { type: "primitive", name: "uint32" },
          flatbuffersFieldNumber: 0,
        },
        {
          name: "b",
          description: "field b",
          type: { type: "primitive", name: "uint32" },
          flatbuffersFieldNumber: 0,
        },
      ],
    };
    expect(() => generateFlatbuffers(schema, [])).toThrow(
      "More than one field with flatbuffersFieldNumber 0",
    );
  });

  it("emits null defaults for optional primitive scalars only", () => {
    const optionalPrimitiveTypes: FoxglovePrimitive[] = [
      "int32",
      "uint32",
      "boolean",
      "float64",
      "string",
      "bytes",
    ];
    const schema: FoxgloveMessageSchema = {
      type: "message",
      name: "OptionalScalars",
      description: "test",
      fields: [
        ...optionalPrimitiveTypes.map((type) => {
          const fieldName = type === "boolean" ? "bool" : type;
          return {
            name: `optional_${fieldName}`,
            description: `optional ${fieldName}`,
            type: { type: "primitive" as const, name: type },
            optional: true as const,
          };
        }),
        {
          name: "optional_scalar_array",
          description: "optional scalar array",
          type: { type: "primitive", name: "int32" },
          array: true,
          optional: true,
        },
      ],
    };

    expect(generateFlatbuffers(schema, [])).toMatchInlineSnapshot(`
      "// Generated by https://github.com/foxglove/foxglove-sdk

      namespace foxglove;

      /// test
      table OptionalScalars {
        /// optional int32
        optional_int32:int32 = null (id: 0);

        /// optional uint32
        optional_uint32:uint32 = null (id: 1);

        /// optional bool
        optional_bool:bool = null (id: 2);

        /// optional float64
        optional_float64:double = null (id: 3);

        /// optional string
        optional_string:string (id: 4);

        /// optional bytes
        optional_bytes:[uint8] (id: 5);

        /// optional scalar array
        optional_scalar_array:[int32] (id: 6);
      }

      root_type OptionalScalars;
      "
    `);
  });

  it("emits null defaults for optional enum fields only", () => {
    const schema: FoxgloveMessageSchema = {
      type: "message",
      name: "OptionalEnums",
      description: "test",
      fields: [
        {
          name: "optional_enum",
          description: "optional enum",
          type: { type: "enum", enum: exampleEnum },
          optional: true,
        },
        {
          name: "optional_enum_array",
          description: "optional enum array",
          type: { type: "enum", enum: exampleEnum },
          array: true,
          optional: true,
        },
      ],
    };

    expect(generateFlatbuffers(schema, [exampleEnum])).toMatchInlineSnapshot(`
      "// Generated by https://github.com/foxglove/foxglove-sdk

      namespace foxglove;

      /// An example enum
      enum ExampleEnum : ubyte {
        /// Value A
        A = 0,

        /// Value B
        B = 1,
      }
      /// test
      table OptionalEnums {
        /// optional enum
        optional_enum:ExampleEnum = null (id: 0);

        /// optional enum array
        optional_enum_array:[ExampleEnum] (id: 1);
      }

      root_type OptionalEnums;
      "
    `);
  });

  it("throws when an optional FlatBuffer scalar field also has a default value", () => {
    const boolSchema: FoxgloveMessageSchema = {
      type: "message",
      name: "OptionalBoolWithDefault",
      description: "test",
      fields: [
        {
          name: "optional_bool_with_default",
          description: "optional bool with default",
          type: { type: "primitive", name: "boolean" },
          optional: true,
          defaultValue: true,
        },
      ],
    };
    const enumSchema: FoxgloveMessageSchema = {
      type: "message",
      name: "OptionalEnumWithDefault",
      description: "test",
      fields: [
        {
          name: "optional_enum_with_default",
          description: "optional enum with default",
          type: { type: "enum", enum: exampleEnum },
          optional: true,
          defaultValue: "A",
        },
      ],
    };

    expect(() => generateFlatbuffers(boolSchema, [exampleEnum])).toThrow(
      'Field "optional_bool_with_default": optional FlatBuffer scalar fields cannot have a default value',
    );
    expect(() => generateFlatbuffers(enumSchema, [exampleEnum])).toThrow(
      'Field "optional_enum_with_default": optional FlatBuffer scalar fields cannot have a default value',
    );
  });
});
