[package]
name = "example_ws_server"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", features = ["schemars"] }
tokio = { version = "1.47", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
quaternion = "2.0.0"
