[package]
name = "example_client_publish"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove" }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0.142"
env_logger = "0.11.5"
