name: Dependabot

on:
  pull_request: {}

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Approve Dependabot PRs
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          event: APPROVE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
